ALTER DATABASE                         SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE        		       SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE        		       SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE        		       SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE        		       SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE        		       SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE        		       SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE        		       SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE        		       SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE        		       SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE        		       SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE        		       SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE        		       SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE        		       SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE        		       SET OFFLINE WITH ROLLBACK IMMEDIATE;
ALTER DATABASE        		       SET OFFLINE WITH ROLLBACK IMMEDIATE;








